### ISSUE TITLE
Tables not present in DB issue

### ISSUE THREAD

**Issue by JrFelix540** [Adam-Rao/Fast-API-Starter#1]
## Tables not present in database issue

- Basically, we need to run migrations in the docker container running the api

### Steps to follow

- Run `docker-compose up`
- Open another terminal and run `docker ps`
- Obtain the container id of the api container, e.g.

```
 CONTAINER ID IMAGE 
 29ef2c8e2b11 fast-api-starter_api

```

- Run `docker exec -it 29ef2c8e2b11 bash` to access the terminal in the api container
- Run `alembic upgrade head` to run the migrations
- You can exit your container's bash by running `exit`

**Comment by AdamR22** [comment]
It works, thanks a lot.
